pipeline {
    agent any
    stages {
        stage('Compile Code') {
            steps {
                sh './mvnw clean compile'
            }
        }
        stage('Unit Test') {
            steps {
                sh './mvnw test'
            }
        }
        stage('Integration Test') {
            steps {
                sh './mvnw verify'
            }
        }
        stage('Package Artifact Jar') {
            steps {
                sh './mvnw package'
            }
        }
    }
}