pipeline {
    agent any
    stages {
        stage('Compile Code') {
            steps {
                sh './mvnw clean compile'
            }
        }
        stage('Unit Test') {
            steps {
                sh './mvnw test'
            }
        }
        stage('Integration Test') {
            steps {
                sh './mvnw verify'
            }
        }
        stage('Package Artifact Jar') {
            steps {
                sh './mvnw package'
            }
        }
        stage('Build Docker Image') {
            environment {
                VERSION = readMavenPom().getVersion()
            }
            steps {
                sh "docker build -t user-service:${VERSION} ."
            }
        }
    }
    post {
        success {
            echo "Build Success"
            echo "Successfully built ${env.JOB_BASE_NAME} - ${env.BUILD_ID} on ${env.BUILD_URL}"
        }
        failure {
            echo "Build Failed - ${env.JOB_BASE_NAME} - ${env.BUILD_ID} on ${env.BUILD_URL}"
        }
        aborted {
            echo " ${env.JOB_BASE_NAME} Build - ${env.BUILD_ID} Aborted!"
        }
    }
}